#!/usr/bin/env node
// Generates TypeScript declarations from the JSON Schema sources.
//
//   src/**/*.schema.json  ->  gen/ts/**/*.d.ts  +  gen/ts/index.d.ts
//
// Output is committed. It must be byte-stable: the banner carries no timestamp,
// the file list is sorted, and prettier settings are pinned here rather than
// picked up from the environment. `pnpm --filter @halo-cad/schema build` twice
// in a row has to leave `git status` clean.
//
// Cross-file `$ref`s are absolute `https://schema.halo-cad.internal/v0/...`
// URLs. The resolver below maps that origin back onto `src/`, so code
// generation never reaches the network.
import { readFile, writeFile, mkdir, readdir, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const PKG_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC_DIR = path.join(PKG_ROOT, "src");
const OUT_DIR = path.join(PKG_ROOT, "gen", "ts");
const SCHEMA_ORIGIN = "https://schema.halo-cad.internal/v0/";

const BANNER = `/* eslint-disable */
/**
 * Generated by packages/schema/scripts/gen-ts.mjs from the JSON Schema sources
 * in packages/schema/src. DO NOT EDIT BY HAND.
 *
 * Change the schema, run \`pnpm --filter @halo-cad/schema build\`, commit both.
 */`;

/** Recursively collect `*.schema.json` under `dir`, relative to `SRC_DIR`, sorted. */
async function collectSchemas(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const found = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...(await collectSchemas(full)));
    } else if (entry.name.endsWith(".schema.json")) {
      found.push(path.relative(SRC_DIR, full));
    }
  }
  return found.sort();
}

/** `common/provenance.schema.json` -> `common/provenance` */
function moduleNameOf(relPath) {
  return relPath.replace(/\.schema\.json$/, "").split(path.sep).join("/");
}

/** Resolve a schema URL back to its file on disk, refusing anything else. */
function schemaUrlToPath(url) {
  const withoutQuery = url.split("#")[0];
  const idx = withoutQuery.indexOf(SCHEMA_ORIGIN);
  if (idx === -1) throw new Error(`refusing to resolve non-local schema ref: ${url}`);
  const rel = withoutQuery.slice(idx + SCHEMA_ORIGIN.length);
  return path.join(SRC_DIR, rel);
}

const $refOptions = {
  resolve: {
    http: false,
    file: { order: 10 },
    haloCadSchema: {
      order: 1,
      canRead: /schema\.halo-cad\.internal/,
      async read(file) {
        return await readFile(schemaUrlToPath(file.url), "utf8");
      },
    },
  },
};

async function main() {
  const relPaths = await collectSchemas(SRC_DIR);
  if (relPaths.length === 0) throw new Error(`no schemas found under ${SRC_DIR}`);

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const barrel = [];
  for (const rel of relPaths) {
    const schema = JSON.parse(await readFile(path.join(SRC_DIR, rel), "utf8"));
    const title = schema.title;
    if (!title) throw new Error(`${rel} has no "title"; it names the generated root type`);

    const ts = await compile(schema, title, {
      bannerComment: BANNER,
      additionalProperties: false,
      declareExternallyReferenced: true,
      // Only emit `$defs` that the root actually reaches, otherwise every
      // definition is declared twice (once inlined, once as `Foo1`). The
      // primitives file is the exception: its root has no properties, so
      // nothing is reachable and the whole point of the file is its `$defs`.
      unreachableDefinitions: rel === "common/primitives.schema.json",
      enableConstEnums: false,
      ignoreMinAndMaxItems: false,
      strictIndexSignatures: false,
      cwd: path.join(SRC_DIR, path.dirname(rel)) + path.sep,
      $refOptions,
      style: {
        printWidth: 100,
        semi: true,
        singleQuote: false,
        tabWidth: 2,
        trailingComma: "es5",
        useTabs: false,
      },
    });

    const outFile = path.join(OUT_DIR, `${moduleNameOf(rel)}.d.ts`);
    await mkdir(path.dirname(outFile), { recursive: true });
    await writeFile(outFile, ts, "utf8");
    barrel.push({ module: moduleNameOf(rel), title });
    process.stdout.write(`  ${rel} -> gen/ts/${moduleNameOf(rel)}.d.ts (${title})\n`);
  }

  const indexBody = barrel
    .map(({ module, title }) => `export type { ${title} } from "./${module}";`)
    .join("\n");
  await writeFile(
    path.join(OUT_DIR, "index.d.ts"),
    `${BANNER}\n\n// Root type of every schema. Inner types live next to them, e.g.\n// \`import type { LineEntity } from "@halo-cad/schema/gen/ts/ndj/entity";\`\n${indexBody}\n`,
    "utf8"
  );
  process.stdout.write(`  ${barrel.length} schemas -> gen/ts/index.d.ts\n`);
}

main().catch((err) => {
  process.stderr.write(`${err instanceof Error ? err.stack : String(err)}\n`);
  process.exitCode = 1;
});
